apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-app
  template:
    metadata:
      labels:
        app: hostpath-app
    spec:
      containers:
      - name: app-container
        image: busybox
        command: ["sleep", "3600"]
        volumeMounts:
        - name: host-storage
          mountPath: /host/data
      volumes:
      - name: host-storage
        hostPath:
          path: /data/logs
          type: DirectoryOrCreate
