apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: app-container
        image: busybox
        command: ["sleep", "3600"]
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-storage
        nfs:
          server: 10.10.10.10 #Server IP address in which NFS mount is created
          path: /shared/data  #Path of NFS mount
