apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-pod
  # namespace: simple-k8s-app
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - port: 80  #This is the port on the Service itself inside the cluster. The Service listens on port 80
      targetPort: 80  #This is the port on the Pod/container that the Service routes traffic to. 
      containerPort: 80 #It tells Kubernetes what port the container (inside the Pod) is listening on.