apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-pod
  # namespace: simple-k8s-app
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - port: 80
      targetPort: 80
      containerPort: 80
    resources:
      requests:   #Minimum resources needed by container
        memory: "64Mi"
        cpu: "250m"
      limits:     #Maximum resources allowed for container. Container terminated if exceeds
        memory: "128Mi"
        cpu: "500m"