apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readiness
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
