apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
#  volumeName: PV-NAME #If you want to bind specific PV to PVC
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
