apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd   #pod will deploy in the node which has this label disktype: ssd
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]