#We don't need to create PV if we are using dynamic provisioning
#But for hostpath dynamic provisioning is not possible in standard k8s clusters. So we have to manually create PV (thats the reason we are creating pv.yaml file)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    type: local
spec:
  storageClassName: storage-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-data
